### PR TITLE
Show users the report guidelines when they're going to submit a report

### PR DESCRIPTION
**Pull request by ghost**
This PR implements the UI for showing the user the report guidelines when they are going to create a report.

> [!Note]
> When the system for creating reports is implemented, that developer should **only** show the guidelines for the users **first** report.

This is what was implemented:

### CODE REVIEW

**Comment by evnd04** [comment]
Is this shown for all reports? Because SOS reports should not have this pop up just in case.

**Comment by evnd04** [comment]
@diego-velez-upr Merge conflicts

**Comment by diego-velez-upr** [comment]
> Is this shown for all reports? Because SOS reports should not have this pop up just in case.

It used to be shown for all reports, but now it doesn't show for SOS reports.

The guidelines should now look like this:

**Comment by evnd04** [comment]
There something wrong, youre pushing 5000+ files

**Comment by diego-velez-upr** [comment]
Oh, somebody renamed our `safe-rum` folder to `safe-rum1` for some reason, and now it's causing confusion.

**Comment by diego-velez-upr** [comment]
@evnd04 it should be ok now.

**Pull request merged**
