### PR TITLE
Add Firebase functionality to backend

### LINKED ISSUE #323: Allow database to receive & store Firebase JWT from user signup
**Objective:**

Enable the backend to securely receive, validate, and store Firebase JWTs from new users upon signup. Storing JWTs will facilitate session management, user validation, and seamless access to resources.

---

**Task Description:**

The task involves setting up the backend to accept Firebase JWTs from users upon signup, validating these tokens, and then storing user information in the database for future reference and validation. The process will include decoding the JWT to extract user details (like UID, email), securely saving relevant details in the database, and storing the token for session management or analytics purposes.

---

**Implementation:**

1. **Receive Firebase JWT on Signup**:
   - Create an API endpoint to handle incoming signup requests containing the Firebase JWT.
   - Extract the token from the request and pass it to the Firebase Admin SDK for validation.

2. **JWT Validation**:
   - Use Firebase Admin SDK to decode and validate the JWT.
   - Retrieve user details like UID, email, and display name from the decoded token payload.

3. **Store User Details in the Database**:
   - Create a user model or table to store essential user details and the JWT, if required.
   - Store fields like Firebase UID, email, display name, signup timestamp, and JWT (optional for analytics, not recommended for long-term storage).

---

**Subtasks:**

1. **Set Up Firebase Admin SDK for JWT Decoding**:
   - Initialize Firebase Admin SDK with the service account to enable JWT decoding and validation.

2. **Implement Signup Endpoint**:
   - Define a POST endpoint (e.g., `/api/signup`) to receive Firebase JWTs and handle new user signup.
   - Use Firebase Admin SDK to decode the token and retrieve user details.

3. **Database Integration**:
   - Create a user table/model with columns like `firebase_uid`, `email`, `display_name`, and optional `jwt` for session tracking or analytics.
   - Save decoded user information into the database upon successful signup.

4. **Environment Configuration**:
   - Securely store Firebase credentials using environment variables.
   - Document environment configuration steps in `.env.example` for secure deployment.

---

**Testing and Debugging:**

- **Unit Testing**: Test the JWT validation logic with valid and invalid tokens to ensure it correctly verifies authenticity.
- **Database Checks**: Manually confirm the stored user details in the database after signup requests to ensure accuracy.

---

**Deadline:**
October 25th, 2024

### LINKED ISSUE #324: Implement Firebase API boilertplate code in backend
**Objective:**

Integrate Firebase Authentication to enable secure user login and session management on the backend. This will provide authentication middleware for verifying user tokens and controlling access to protected routes.

---

**Task Description:**

The task involves setting up Firebase Authentication in the backend to handle user login sessions. This setup will include initializing Firebase Auth, creating middleware to verify ID tokens from Firebase, and defining a login route if needed to verify credentials or initiate user sessions. 

---

**Implementation:**

1. **Set Up Firebase Admin SDK for Authentication**:
   - Obtain Firebase service account credentials and initialize the Firebase Admin SDK.
   - Configure environment variables to securely store Firebase API keys and service credentials.

2. **Token Verification Middleware**:
   - Create middleware to verify Firebase ID tokens in incoming requests.
   - Decode the ID token to retrieve user information and enforce access control where necessary.

3. **Login Endpoint** (if custom token or additional processing is needed):
   - Optionally set up an endpoint to handle client login requests if additional processing (e.g., role checks) is required.
   - Use the Firebase Admin SDK to verify the token and respond with user info or session details.

---

**Subtasks:**

1. **Setup Firebase Admin SDK with Service Account**:
   - Initialize Firebase in the backend using credentials from the team app.

2. **Implement Authentication Middleware**:
   - Write middleware to validate incoming Firebase ID tokens.
   - Extract user info from tokens for additional session logic if needed.

3. **Environment Setup**:
   - Store Firebase keys and service credentials in environment variables for secure configuration.
   - Document configuration steps and required environment variables in a `.env` file.

---

**Testing and Debugging:**

- **Unit Testing**: Test the token verification middleware to ensure it correctly validates and rejects invalid tokens.
- **Manual Testing**: Test with Firebase’s generated tokens from the frontend to confirm successful login and access control.

---

**Deadline:**
October 25th, 2024

### LINKED ISSUE #326: Allow connections to backend to authenticate with JWT
**Objective:**

Enable backend connections to require Firebase JWT authentication, ensuring secure access to protected resources. This will prevent unauthorized access and allow seamless session management based on Firebase Authentication.

---

**Task Description:**

The task is to implement JWT-based authentication in the backend by verifying Firebase JWTs for all incoming requests that require authentication. The setup will involve creating middleware to validate tokens, retrieving user details from the token, and attaching this information to the request for role-based access control and personalized responses.

---

**Implementation:**

1. **Setup Firebase Admin SDK**:
   - Initialize the Firebase Admin SDK using service account credentials for JWT validation.
   - Securely store Firebase credentials in environment variables for safe access.

2. **JWT Verification Middleware**:
   - Develop middleware to verify Firebase JWTs by decoding and validating them using the Firebase Admin SDK.
   - Extract user details from the token (e.g., UID, email) and attach them to the request object for downstream use in routes.

3. **Apply Middleware to Protected Routes**:
   - Add the JWT verification middleware to routes that require authentication.
   - Ensure the middleware rejects requests with invalid, expired, or missing tokens.

---

**Subtasks:**

1. **Initialize Firebase Admin SDK**:
   - Securely configure Firebase using service account credentials.
   - Use environment variables to manage sensitive information.

2. **Implement JWT Middleware**:
   - Create middleware to decode and verify incoming Firebase JWTs.
   - Attach user information to requests to enable personalized and secure access to resources.

3. **Integrate Middleware with Routes**:
   - Apply the middleware to routes that require authentication.
   - Test routes to confirm access restrictions are correctly enforced.

4. **Testing and Logging**:
   - Add logging for authentication events (e.g., token validation success/failure) to simplify debugging and monitoring.

---

**Testing and Debugging:**

- **Manual Testing**: Send requests with various tokens to verify proper access control.
- **Error Handling**: Implement error handling for missing or expired tokens to return clear error messages.

---

**Deadline:**
October 25th, 2024

### PR DESCRIPTION
**Pull request by joel-alvarado**
Fixes #323 
Fixes #324 
Fixes #326

Recommend squash and merge since commit history is a bit dirty

### CODE REVIEW

**Comment by evnd04** [comment]
Is this ready to merge? Add any reviewers you think could review.

**Comment by joel-alvarado** [comment]
> Is this ready to merge? Add any reviewers you think could review.

Yep, it's ready. Will add reviewers soon.

**Review by noel-vargas — COMMENTED** [review]
I see some TODO's on the code but for the purposes of this task everything looks ok.

**Review by JuanJRivera — APPROVED** [review]

**Comment by JuanJRivera** [comment]
LGTM!

**Review by noel-vargas — APPROVED** [review]

**Pull request merged**
