### PR TITLE
Implement the report editing UI

### LINKED ISSUE #115: Implement the report editing UI
## Objective
Implement the UI for editing a report

> [!Note]
> This issue depends on the task #110  (Design the report editing UI)

## Task Description
Implement the UI for editing a report. The implementation will follow the design of the report editing system.

## Implementation
Since the system to be will be accepting user input, **it must sanitize/validate said input** in order to ensure that the code is as secure as possible, and minimize the surface area for attacks. The System must make sure that the user editing the report has permission to do so, if the user does not, under no circumstances should the user not be allowed to edit the report. 

## Testing
Unit testing that verifies that the UI was drawn as expected, and that its behavior works as expected should be implemented.
Unit testing must also verify that the edit is successfully reflected in the database.
Unit testing that verifies that the report displayed that is has been edited.

## Deadline
Milestone 1

### PR DESCRIPTION
**Pull request by ghost**
## Summary
This PR allows users to edit reports (completes #115).

## Changes
- Implement an edit mode state for the view report component
    - Users can edit their changes and apply them using the edit button
- Code optimization and refactoring
- Added Prettier config to enforce project wide styling

## Screenshots
The following screenshots showcase the new workflow: view report -> edit report -> apply edit.

Viewing report

Editing report

Applying edit

### CODE REVIEW

**Comment by YanehRuiz** [comment]
Could you please change the title label from "View Report" to "Report Editing" to better reflect its function, when it's being edited? Thank you!

**Review by evnd04 — APPROVED** [review]
Looks good to me!

**Comment by YanehRuiz** [comment]
@diego-velez-upr Just a reminder that I can merge this issue once the changes are in ^^

**Review by YanehRuiz — APPROVED** [review]

**Comment by diego-velez-upr** [comment]
Changed the header of the view report view to show when the user is in edit mode or in view mode.

This is how it should look now when the user is in edit mode:

**Comment by diego-velez-upr** [comment]
@YanehRuiz

**Pull request merged**
